### ISSUE TITLE
Rollcall attendance can not authorize from my course

### ISSUE THREAD

**Issue by bacao1994** [instructure/rollcall-attendance#164]
I set up a canvas and roll call attendance on my laptop. I have generated CANVAS_KEY and CANVAS_SECRET. But, I can not authorize the roll call attendance in my courses. Please give me some advice for tracing this case. Many thanks.
Case 1: I got an error: Canvas doesn't open any link for me to authorize the course and it shows an error below:
         "The OAuth signature was invalid. Please be sure you are launching this tool from the link provided in Canvas."
Case 2: The canvas has opened a link for me to authorize. After that, It shows an invalid code: c70288c616182151f035aaff6730370848ae8ecd20c2d3376cabfd69a329199587a3e26117df1244cb0dc3d6ca32a36ae885ddfb35046aa76173363e78  
![Screenshot from 2022-06-16 10-00-29](https://user-images.githubusercontent.com/44079615/173981912-0fa2eb87-3c3b-43a7-af9b-1d6fe21cd323.png)
![Screenshot from 2022-06-16 10-01-00](https://user-images.githubusercontent.com/44079615/173981956-73e82998-b627-4f80-90a9-60f19c84cee7.png)
![Screenshot from 2022-06-16 10-38-13](https://user-images.githubusercontent.com/44079615/173985880-dd4c8d84-219c-4908-937c-16e80331ebee.png)

**Comment by bacao1994** [comment]
I found the same issue at 
https://github.com/instructure/rollcall-attendance/issues/127

**Comment by dqcuong93** [comment]
Hi, I have met the same problem as your case 1. Could you please tell me how to fix it?
